version: '3.8'

services:

  db:
    image: postgres:13.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=torqata
    ports:
      - 5432:5432