name: Deploy to GAE

on:
  push:
    branches: [ develop ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_APP_ENV: PROD
        envkey_API_DOMAIN: ${{ secrets.API_DOMAIN }}
        envkey_POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        envkey_POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
        envkey_NEO4J_PROTOCOL: ${{ secrets.NEO4J_PROTOCOL }}
        envkey_NEO4J_HOST: ${{ secrets.NEO4J_HOST }}
        envkey_NEO4J_PORT: ${{ secrets.NEO4J_PORT }}
        envkey_NEO4J_USER: ${{ secrets.NEO4J_USER }}
        envkey_NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        file_name: .env
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}
    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"

